spring.application.name=setu

#Context Path Detail
server.servlet.context-path=/SwasthyaSetu


### DataSource Configuration for PRODUCTION
spring.datasource.url=jdbc:oracle:thin:@172.24.200.88:1521:orcl
spring.datasource.username=reg_system
spring.datasource.password=reg_system

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

## Hibernate Configuration with Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true